// <auto-generated />
using DSB.StreamBackend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSB.StreamBackend.Migrations
{
    [DbContext(typeof(StreamToolDbContext))]
    [Migration("20260528092511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DSB.StreamBackend.Models.BroadcastStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlphaIsLeft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentator1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentator2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreAlpha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreBravo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCommentatorBox")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInfobox")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMapScreen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowScoreBox")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamAlphaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamBravoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BroadcastStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlphaIsLeft = true,
                            Commentator1 = "",
                            Commentator2 = "",
                            ScoreAlpha = 0,
                            ScoreBravo = 0,
                            ShowCommentatorBox = true,
                            ShowInfobox = true,
                            ShowMapScreen = true,
                            ShowScoreBox = true,
                            TeamAlphaName = "Team Alpha",
                            TeamBravoName = "Team Bravo"
                        });
                });

            modelBuilder.Entity("DSB.StreamBackend.Models.MapStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BroadcastStateEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BroadcastStateEntityId");

                    b.ToTable("MapStates");
                });

            modelBuilder.Entity("DSB.StreamBackend.Models.MapStateEntity", b =>
                {
                    b.HasOne("DSB.StreamBackend.Models.BroadcastStateEntity", "BroadcastState")
                        .WithMany("Maps")
                        .HasForeignKey("BroadcastStateEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BroadcastState");
                });

            modelBuilder.Entity("DSB.StreamBackend.Models.BroadcastStateEntity", b =>
                {
                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
