name: Run .NET Tests CI

permissions:
    contents: read

on:
    workflow_run:
        workflows: ["Build .NET CI"]
        types:
            - completed
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    test:
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Build .NET CI' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x
            - name: Restore dependencies
              run: dotnet restore tests/DSB.StreamBackend.Tests/DSB.StreamBackend.Tests.csproj
            - name: Run Backend Unit Tests
              run: dotnet test --verbosity normal tests/DSB.StreamBackend.Tests/DSB.StreamBackend.Tests.csproj
