name: Run Node.js Tests CI
permissions:
    contents: read

env:
    FRONTEND_PATH: ./Frontend/control-panel

defaults:
    run:
        shell: bash

on:
    workflow_run:
        workflows: ["Build Node.js CI"]
        types:
            - completed
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build:
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Build Node.js CI' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
                  cache-dependency-path: ${{ env.FRONTEND_PATH }}/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: ${{ env.FRONTEND_PATH }}
            - name: Install Angular CLI
              run: npm install -g @angular/cli
              working-directory: ${{ env.FRONTEND_PATH }}
            - name: Install @vitest/browser-playwright
              run: npm install @vitest/browser-playwright
            - name: Set Up Playwright
              run: npx playwright install
              working-directory: ${{ env.FRONTEND_PATH }}
            - name: Run Node.js Tests
              run: npm test
              working-directory: ${{ env.FRONTEND_PATH }}
