name: Run .NET Tests CI

permissions:
    contents: read

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x
            - name: Restore dependencies
              run: dotnet restore tests/DSB.StreamBackend.Tests/DSB.StreamBackend.Tests.csproj
            - name: Run Backend Unit Tests
              run: dotnet test --verbosity normal tests/DSB.StreamBackend.Tests/DSB.StreamBackend.Tests.csproj
