# This workflow will check the Frontend typescript code for quality with typescript-eslint
# For more information see: https://typescript-eslint.io

name: TypeScript Code Quality CI

env:
    FRONTEND_PATH: ./Frontend/control-panel

defaults:
    run:
        shell: bash

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: ${{ env.FRONTEND_PATH }}/package-lock.json
            - name: Install dependencies
              run: npm ci
              working-directory: ${{ env.FRONTEND_PATH }}
            - name: Check TypeScript code quality
              run: npx eslint src/ --format gha
              working-directory: ${{ env.FRONTEND_PATH }}
